name: exercise_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  rxdart: ^0.27.6

  # SVG
  flutter_svg: ^1.1.6
  
  # Quick Widget
  getwidget: ^3.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/